### ISSUE TITLE
Contribute.md file missing

### ISSUE THREAD

**Issue by shyanukant** [robogyan-adgitm/robogyan-adgitm.github.io#10]
According to hacktoberfest guidelines there should be a contributing.md file in projects participating in hacktoberfest.
please assign this issue to me...

**Comment by robogyan-adgitm** [comment]
go ahead @shyanukant

**Comment by BTANISHA11** [comment]
I want to work on contibutor.md
can you pls assign this to me @robogyan-adgitm
