### ISSUE TITLE
Change the logo on every page.

### ISSUE THREAD

**Issue by robogyan-adgitm** [robogyan-adgitm/robogyan-adgitm.github.io#116]
Replace the logo on every page by just "Robogyan" in the font "Russo One"

[Google Fonts](https://fonts.google.com/specimen/Russo+One?query=Robogyan&preview.text=Robogyan&preview.text_type=custom)

**Comment by robogyan-adgitm** [comment]
Font Color: White (over any dark background)

**Comment by Aakriti-malla** [comment]
Hey! I can make the changes. Kindly assign it to me!

**Comment by ghost** [comment]
Hey!
Can you please assign this issue to me?
