### ISSUE TITLE
To redesign Our Objective Page

### ISSUE THREAD

**Issue by rahulkathuriaaa** [robogyan-adgitm/robogyan-adgitm.github.io#124]
I will make the page more appealing and eye catching with more graphical representations of objectives and future plans of robogyan.

**Comment by rahulkathuriaaa** [comment]
Assign me this task

**Comment by rahulkathuriaaa** [comment]
Thankyou

**Comment by Yash-Sajwan24** [comment]
I will make the page eye-catching and user-friendly. Assign me this task.
