### ISSUE TITLE
Improvement in the join Robogyan today section

### ISSUE THREAD

**Issue by Yash-Sajwan24** [robogyan-adgitm/robogyan-adgitm.github.io#127]
The content is just randomly arranged without any CSS. Assign me this task. 
![Screenshot 2022-10-24 103436](https://user-images.githubusercontent.com/52412969/197452247-d1b82651-16a1-4fd3-ab4c-a02849f667c4.png)

**Comment by robogyan-adgitm** [comment]
Go ahead with it
