### ISSUE TITLE
Create an empty about us page

### ISSUE THREAD

**Issue by robogyan-adgitm** [robogyan-adgitm/robogyan-adgitm.github.io#24]
In this issue we expect to have a page named "About Us" with url "https://robogyan-adgitm.github.io/about.html" or "https://robogyan-adgitm.github.io/about". And add its link to homepage.

**Comment by Sammydepoj** [comment]
Hello, i would like to work on this, kindly assign me

**Comment by robogyan-adgitm** [comment]
Go ahead @Sammydepoj
