### ISSUE TITLE
Add content to about us page

### ISSUE THREAD

**Issue by robogyan-adgitm** [robogyan-adgitm/robogyan-adgitm.github.io#25]
In this issue we expect you to add properly formatted content to/for out about us page cretaed in another issue ( https://github.com/robogyan-adgitm/robogyan-adgitm.github.io/issues/24 )

**Comment by Priyanshu-su30** [comment]
Pls assign me this

**Comment by robogyan-adgitm** [comment]
Go ahead @Priyanshu-su30

**Comment by Mrsingh782** [comment]
Can you please assign me on this issue.

**Comment by robogyan-adgitm** [comment]
Go ahead @Mrsingh782

**Comment by deepanshu-sharmaa** [comment]
@robogyan-adgitm please assign this issue.

**Comment by robogyan-adgitm** [comment]
Go ahead @deepanshu-sharmaa

**Comment by ayushigeorge** [comment]
Can I contribute as well?

**Comment by robogyan-adgitm** [comment]
Go ahead @ayushigeorge

**Comment by JayantDane123** [comment]
Hello sir ,
please assign me for this issues
I ensure to complete it

**Comment by robogyan-adgitm** [comment]
Go ahead @JayantDane123

**Comment by aksha123-git** [comment]
I would like to contribute on this issues please assign it to me @robogyan-adgitm

**Comment by robogyan-adgitm** [comment]
Go ahead @aksha123-git

**Comment by varunsood2003** [comment]
Hey I'm new to open source contribution but would love to work and learn with you can you assign me a issue ?

**Comment by robogyan-adgitm** [comment]
Go ahead @varunsood2003

**Comment by robogyan-adgitm** [comment]
I would request everyone to star the repo as a token of appreciation if you enjoyed contributing here
