### ISSUE TITLE
Add style to FAQ page

### ISSUE THREAD

**Issue by app-src** [robogyan-adgitm/robogyan-adgitm.github.io#41]
In this issue you can contribute by adding some content to FAQ page with some FAQ section like styling, expandable drawers for answers and tiled questions. Content could be anything for now.

**Comment by Akshay-21** [comment]
Hey hi @robogyan-adgitm, can you assign this issue. I want to work on this.

**Comment by robogyan-adgitm** [comment]
Go ahead @Akshay-21

**Comment by Akshay-21** [comment]
Hey Hi @robogyan-adgitm i added style in FAQ Page. I have created PR kindly check this.
Thank You!

**Comment by Akshay-21** [comment]
Hey Hi @robogyan-adgitm, after creating PR here conflict was showing so i resolved this conflict issue and push the updated code. kindly check this and mege it.

Thank You.

**Comment by Akshay-21** [comment]
This happened because of someone push the code directly into main in the same file at time of when i was working.

**Comment by Akshay-21** [comment]
hey hi @robogyan-adgitm is there any issue in this pull request?

**Comment by robogyan-adgitm** [comment]
Already answered on PR @Akshay-21

**Comment by Akshay-21** [comment]
Hi @robogyan-adgitm, i have removed unused file and code and personal info, i have updated FAQ Accordion using smooth design with theme matching.

and also resolved conflict file.

kindly check this.

Thank You!

![image](https://user-images.githubusercontent.com/32409386/194653540-a104cd1a-f886-4836-9338-2e465cde0657.png)

**Comment by varunsood2003** [comment]
Hey I'm new to open source contribution but would love to work and learn with you can you assign me a issue ?

**Comment by robogyan-adgitm** [comment]
I would request everyone to star the repo as a token of appreciation if you enjoyed contributing
