### ISSUE TITLE
Login and Signup 

### ISSUE THREAD

**Issue by sanyayaa** [robogyan-adgitm/robogyan-adgitm.github.io#5]
I want to add Login and Signup button.

Kindly assign me this issue.

**Comment by robogyan-adgitm** [comment]
can you link "Apply now" button to https://forms.gle/BZpCaHyXaEnzpzP67 ?

**Comment by sanyayaa** [comment]
yess

**Comment by robogyan-adgitm** [comment]
Go ahead @sanyayaa

**Comment by sanyayaa** [comment]
Is it not okay?

**Comment by robogyan-adgitm** [comment]
It is, just different from planned.

**Comment by sanyayaa** [comment]
@robogyan-adgitm what changes do you want exactly
