### ISSUE TITLE
Add content to FAQ page

### ISSUE THREAD

**Issue by robogyan-adgitm** [robogyan-adgitm/robogyan-adgitm.github.io#50]
In this issue we expect to have some relevant improvement in terms of content in FAQ page.

**Comment by Manoj0Marmat** [comment]
@robogyan-adgitm i can help with it

**Comment by RohitShah1706** [comment]
@robogyan-adgitm 
I have decent experience in React, SCSS bootstrap. 
Please assign this issue to me.

**Comment by robogyan-adgitm** [comment]
Go ahead @RohitShah1706 & @Manoj0Marmat

**Comment by RohitShah1706** [comment]
Hey @robogyan-adgitm please guide
What kind of relevant info do you want in FAQ page.

**Comment by robogyan-adgitm** [comment]
Explore "Robogyan" yourself @RohitShah1706 :smile:

**Comment by Manoj0Marmat** [comment]
@RohitShah1706 and @robogyan-adgitm faq page totally damaged please check this issue #52

**Comment by varunsood2003** [comment]
Hey I'm new to open source contribution but would love to work and learn with you can you assign me a issue ?

**Comment by robogyan-adgitm** [comment]
I would request everyone to star the repo as a token of appreciation if you enjoyed contributing
