### ISSUE TITLE
Issue: bootstrap causing navbar styling and faq not working without bootstrap

### ISSUE THREAD

**Issue by Manoj0Marmat** [robogyan-adgitm/robogyan-adgitm.github.io#52]
Issue:

![Screen Recording 2022-10-07 at 10 17 13 PM](https://user-images.githubusercontent.com/85970385/194611626-f3953594-e394-4199-88d7-e5e78c3d9fd3.gif)

navbar destroyed because of bootstrap
faq completely depend on bootstrap
Solution:
need to create FAQ without boostrap

**Comment by Manoj0Marmat** [comment]
@robogyan-adgitm please review it and assign me to solve this issue

**Comment by Manoj0Marmat** [comment]
@robogyan-adgitm check #56 pr i resolved lot of issues

**Comment by Manoj0Marmat** [comment]
@robogyan-adgitm kindly review it

**Comment by Manoj0Marmat** [comment]
@vanshgupta-2024 kindly review this issue

**Comment by robogyan-adgitm** [comment]
Issue Assigned to you @Manoj0Marmat

**Comment by Manoj0Marmat** [comment]
@robogyan-adgitm solved
