### ISSUE TITLE
Add Content for Terms of Use and Privacy Policy 

### ISSUE THREAD

**Issue by hardik-pratap-singh** [robogyan-adgitm/robogyan-adgitm.github.io#63]
I want to add the content and styling for Terms of Use and Privacy Policy !

I want to work on this issue ! 
May I ?

**Comment by robogyan-adgitm** [comment]
Go ahead @hardik-pratap-singh

**Comment by hardik-pratap-singh** [comment]
Sir,
I have added Privacy Policy (privacy_policy.html) and Terms of Use (terms_of_use.html) to the website. These pages are in sync with the rest of the project. I have made the PR ( #67 ) !

Kindly review my PR.
Please let me know your feedback.

Thanks a lot !

- Privacy Policy
![image](https://user-images.githubusercontent.com/97048877/194711583-c4f65a4c-9d3e-42d6-9efa-28bd5931a4a7.png)

- Terms Of Use
![image](https://user-images.githubusercontent.com/97048877/194711640-6bb70396-8cd9-47da-b2c1-40764d3f4420.png)

**Comment by sauravraj188** [comment]
i am new to open source and so  interesed to work on it ,
ca u please assign to me.
