### ISSUE TITLE
Importance of Robotics

### ISSUE THREAD

**Issue by Devesh18Sharma** [robogyan-adgitm/robogyan-adgitm.github.io#64]
There should be a Slide/container related to robotics importance ...
And How the future is of Robotics and How Robogyan is helping in providing essential information to ADGITM students...
I want to work on it and make it a special feature for your website ...
Do assign it to me...
Regards...

**Comment by robogyan-adgitm** [comment]
Great initiative @Devesh18Sharma Go ahead
