### ISSUE TITLE
To add overlayed video on home page

### ISSUE THREAD

**Issue by rahulkathuriaaa** [robogyan-adgitm/robogyan-adgitm.github.io#90]
Problem:
The design look really basic 

Solution;
I will add theme video for robogyan and will design the web page more attractive

**Comment by robogyan-adgitm** [comment]
Go ahead @rahulkathuriaaa

**Comment by robogyan-adgitm** [comment]
Do you have any ideas for theme video? @rahulkathuriaaa

**Comment by rahulkathuriaaa** [comment]
### These are some videos, I found on internet:

1. https://www.pexels.com/video/a-child-playing-with-educational-toys-7730388/
2. https://www.pexels.com/video/girl-using-a-laptop-7729824/
3. https://www.pexels.com/video/kids-writing-on-the-digital-board-7729815/
4. https://www.pexels.com/video/a-girl-holding-a-robot-7729826/
5. https://www.pexels.com/video/young-engineers-developing-robots-7729820/
6. https://www.pexels.com/video/engineers-working-on-a-robot-9244545/

Do let me know what you think.

**Comment by robogyan-adgitm** [comment]
how about https://we.tl/t-bFmYTj4tvZ ?

**Comment by rahulkathuriaaa** [comment]
okay I will start working on it

**Comment by robogyan-adgitm** [comment]
Great work
