### ISSUE TITLE
back to top button

### ISSUE THREAD

**Issue by anuragasawa20** [robogyan-adgitm/robogyan-adgitm.github.io#96]
I want to add back to top button on website please assign it to me under hacktober fest tag

**Comment by robogyan-adgitm** [comment]
@anuragasawa20 don't we have one already?

**Comment by A1Kumari** [comment]
the style for the same is not so good So I would like to work on this issue to improve it css a little bit.

**Comment by anuragasawa20** [comment]
@robogyan-adgitm  It exist but I want to add in more style and it will be come when we just scroll little bit using javascript so please assign it to me

**Comment by robogyan-adgitm** [comment]
Go ahead @A1Kumari  & @anuragasawa20
