### ISSUE TITLE
project section 

### ISSUE THREAD

**Issue by A1Kumari** [robogyan-adgitm/robogyan-adgitm.github.io#97]
the website does not redirect to any project section page when the project part is clicked on the navbar. I would like to work on the same.
we could have a carousel card-like thing with a hover effect when hovered will show some details about the project and when the img part is clicked for the same it will redirect to the GitHub repo or some other link where that project is available.

**Comment by robogyan-adgitm** [comment]
Go ahead @A1Kumari
